export const ADD_MOVIE_FAVORITE = "ADD_MOVIE_FAVORITE";
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIES_DETAIL = "GET_MOVIES-DETAIL";
export const REMOVE_MOVIES_FAVORITE = "REMOVE_MOVIES_FAVORITE";
